backend:
  name: git-gateway
  branch: main

media_folder: "assets/blog" # Onde as imagens dos posts serão salvas
public_folder: "/assets/blog"

collections:
  - name: "blog" # Identificador da coleção
    label: "Blog"
    label_singular: "Post"
    folder: "_posts" # O CMS agora criará arquivos .json dentro desta pasta
    create: true # Habilita o botão "Novo Post"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Define o nome do arquivo, ex: 2024-05-30-meu-post.json
    extension: "json"
    description: "Crie e edite os artigos do blog aqui."
    fields: # Os campos para preencher em cada post
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - {
          label: "Imagem de Capa",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Resumo", name: "summary", widget: "text" }
      - {
          label: "Autor",
          name: "author",
          widget: "string",
          default: "Dr. Gabriel Marcondes",
        }
      - { label: "Conteúdo do Post", name: "body", widget: "rich_text" }
