backend:
  name: github
  repo: eliezertsilva/site-drgabriel # Substitua se o repositório for outro
  branch: main # Verifique se este é o branch principal
  auth_endpoint: /api/auth # Endpoint para autenticação na Vercel

media_folder: "assets/img" # Onde as imagens serão salvas
public_folder: "/assets/img" # Como as imagens serão acessadas no site

collections:
  - name: "posts"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "json" # Salvar posts como arquivos .json
    format: "json" # Usar o formato JSON
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "image", widget: "image" }
      - {
          label: "Autor",
          name: "author",
          widget: "string",
          default: "Dr. Gabriel Marcondes",
        }
      - { label: "Resumo", name: "summary", widget: "text" }
      - { label: "Corpo do Post", name: "body", widget: "rich_text" }
