backend:
  name: github
  repo: eliezertsilva/site-drgabriel # Ex: DrGabrielMarcondes/site
  branch: main # ou master, dependendo do seu repositório

media_folder: "assets/img" # Onde as imagens serão salvas
public_folder: "/assets/img" # Como as imagens serão acessadas no site

collections:
  - name: "posts"
    label: "Posts do Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "image", widget: "image" }
      - {
          label: "Autor",
          name: "author",
          widget: "string",
          default: "Dr. Gabriel Marcondes",
        }
      - { label: "Resumo", name: "summary", widget: "markdown" }
      - { label: "Corpo do Post", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Páginas"
    files:
      - file: "endometriose.html"
        label: "Página Endometriose"
        name: "endometriose"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }
      # Você pode adicionar outras páginas aqui, como planejamento-familiar.html
